//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementData.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Book_Reservation = new HashSet<Book_Reservation>();
        }
    
        public int isbn_number { get; set; }
        public string authno { get; set; }
        public string title { get; set; }
        public string edition { get; set; }
        public string category { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<int> publisher_id { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<double> price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Reservation> Book_Reservation { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
